name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install Poetry
      uses: snok/install-poetry@v1
    - name: Install ffmpeg
      run: sudo apt update && sudo apt install ffmpeg --yes
    - name: Install package
      run: poetry install -n
    - name: Run tests
      run: ./test.sh
