name: Test

on: [push]

jobs:

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11']
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Poetry
      uses: snok/install-poetry@v1
    - name: Install package
      run: poetry install
    - name: Test
      run: poetry run pytest

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install Poetry
      uses: snok/install-poetry@v1
    - name: Install package
      run: poetry install
    - name: mypy
      run: poetry run mypy --install-types --non-interactive video_object_detector
    - name: black
      run: poetry run black --check video_object_detector
    - name: isort
      run : poetry run isort --check video_object_detector
    - name: flake8
      run: poetry run flake8 video_object_detector
